In [1]:
import pandas as pd 
import matplotlib.pyplot as plt
import numpy as np
from datetime import datetime as dt

In [2]:
tenants = "Tenant_History.csv"
tenants_df = pd.read_csv(tenants)
tenants_df.head()

C:\Users\basis\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (1,4,8,17,18,19,20,21,22,25) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,ResTenantHistory,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,Property_Code,Ref_Property_ID,Date,Tenant_Code,Ext_Ref_Tenant_Id,Event,DateOccurred,Unit_Code,Ref_Unit_Id,DateApply,...,DateNotice,RentedEvent,UnRentedEvent,Status,Rent,Deposit,Sqft,Notes,Reason,MTM
1,sh,NaN,11/18/2016,t0031357,NaN,Deposit Change,11/22/2016,WC5956H,NaN,11/16/2016,...,NaN,0,0,2,641,99,0,NaN,NaN,0
2,ce,NaN,11/22/2016,t0031261,NaN,Deposit Change,11/22/2016,M0008A,NaN,11/3/2016,...,NaN,0,0,0,728,708,0,NaN,NaN,0
3,ce,NaN,11/18/2016,t0031367,NaN,Deposit Change,11/22/2016,M0008A,NaN,11/17/2016,...,NaN,0,0,9,728,50,0,NaN,NaN,0
4,ce,NaN,11/18/2016,t0031350,NaN,Deposit Change,11/22/2016,M0012B,NaN,11/16/2016,...,NaN,0,0,9,888,50,0,NaN,NaN,0

In [3]:
tenants_df = tenants_df.drop(columns = ["Ref_Property_ID", "Ext_Ref_Tenant_Id", "Ref_Unit_Id", "Date"])

KeyError: "labels ['Ref_Property_ID' 'Ext_Ref_Tenant_Id' 'Ref_Unit_Id' 'Date'] not contained in axis"

In [ ]:
tenants_df["DateOccurred"] = pd.to_datetime(tenants_df["DateOccurred"], format= '%m/%d/%Y')
tenants_df["DateApply"] = pd.to_datetime(tenants_df["DateApply"], format= '%m/%d/%Y')
tenants_df["DateApprove"] = pd.to_datetime(tenants_df["DateApprove"], format= '%m/%d/%Y')
tenants_df["DateSign"] = pd.to_datetime(tenants_df["DateSign"], format= '%m/%d/%Y')
tenants_df["DateMoveIn"] = pd.to_datetime(tenants_df["DateMoveIn"], format= '%m/%d/%Y')
tenants_df["DateMoveOut"] = pd.to_datetime(tenants_df["DateMoveOut"], format= '%m/%d/%Y')
tenants_df["DateLeaseFrom"] = pd.to_datetime(tenants_df["DateLeaseFrom"], format= '%m/%d/%Y')
tenants_df["DateLeaseTo"] = pd.to_datetime(tenants_df["DateLeaseTo"], format= '%m/%d/%Y')
tenants_df["DateNotice"] = pd.to_datetime(tenants_df["DateNotice"], format= '%m/%d/%Y')
tenants_df["Length of Stay"]= tenants_df["DateMoveOut"] - tenants_df["DateMoveIn"]
tenants_df.sort_values(by=["Unit_Code"])

In [ ]:
occupancy = tenants_df.sort_values(["DateOccurred", "Tenant_Code"])
occupancy = occupancy.drop(columns = ["DateApply", "DateApprove", "DateSign", "DateLeaseFrom", "DateLeaseTo", "DateNotice", "RentedEvent", "UnRentedEvent", "Status", "Deposit", "Notes", "Reason", "MTM"])
filter = ["Move In", "Move Out", "Rent Change"]
occupancy = occupancy.loc[occupancy["Event"].isin(filter)]
occupancy.reset_index(drop = True)

In [ ]:
def vacancy (row):
    if row["Event"] == "Move Out":
        return 1
    elif row["Event"] == "Move In":
        return 0
    else:
        return 0
    
occupancy ["Vacancy"] = occupancy.apply(vacancy, axis = 1) 
occupancy ["Vacancy"] = occupancy.Vacancy.astype(int)
occupancy.head()

In [ ]:
occupancy = occupancy.sort_values(["Tenant_Code", "DateOccurred"])
occupancy

In [ ]:
def vacancy (row):
    if row["Event"] == "Move Out":
        return "1"
    elif row["Event"] == "Move In":
        return "0"
    else:
        return "0"