In [2]:
import pandas as pd 
import matplotlib.pyplot as plt
import numpy as np

In [3]:
tenants = "Tenant_History.csv"
tenants_df = pd.read_csv(tenants)
tenants_df.head()

C:\Users\Lena\Anaconda3\envs\threesix\lib\site-packages\IPython\core\interactiveshell.py:3020: DtypeWarning: Columns (1,4,8,17,18,19,20,21,22,25) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,ResTenantHistory,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,Property_Code,Ref_Property_ID,Date,Tenant_Code,Ext_Ref_Tenant_Id,Event,DateOccurred,Unit_Code,Ref_Unit_Id,DateApply,...,DateNotice,RentedEvent,UnRentedEvent,Status,Rent,Deposit,Sqft,Notes,Reason,MTM
1,sh,NaN,11/18/2016,t0031357,NaN,Deposit Change,11/22/2016,WC5956H,NaN,11/16/2016,...,NaN,0,0,2,641,99,0,NaN,NaN,0
2,ce,NaN,11/22/2016,t0031261,NaN,Deposit Change,11/22/2016,M0008A,NaN,11/3/2016,...,NaN,0,0,0,728,708,0,NaN,NaN,0
3,ce,NaN,11/18/2016,t0031367,NaN,Deposit Change,11/22/2016,M0008A,NaN,11/17/2016,...,NaN,0,0,9,728,50,0,NaN,NaN,0
4,ce,NaN,11/18/2016,t0031350,NaN,Deposit Change,11/22/2016,M0012B,NaN,11/16/2016,...,NaN,0,0,9,888,50,0,NaN,NaN,0

In [5]:
tenants_df = tenants_df.drop(columns = ["Ref_Property_ID", "Ext_Ref_Tenant_Id", "Ref_Unit_Id"])

TypeError: drop() got an unexpected keyword argument 'header'

In [ ]:
rent_change = tenants_df.loc[tenants_df["Event"] == "Rent Change"]
rent_change = rent_change.groupby("Property_Code")
rent_change.head(25)

In [ ]:
sh = tenants_df.loc[tenants_df["Property_Code"] == "sh"]
sh_rent = sh.loc[sh["Event"] == "Rent Change"]
sh_rent.head(25)

In [ ]:
moveout = tenants_df.dropana(subset = ["DateMoveOut"])
moveout.head(25)

In [153]:
#sh_rent['DateOccurred'] = sh_rent['DateOccured'].astype('datetime64[ns]')
new = sh_rent["DateOccurred"].str.split("/", n = 3, expand = True)
month =[]
day = []
year = []
for x in new[0]:
    if len(x) < 2:
        x = str("0")+str(x)
    month.append(x)
for x in new[1]:
    if len(x) < 2:
        x = str("0")+str(x)
    day.append(x)
for x in new[2]:
    year.append(x)
newdate =[]
for x in range(len(day)):
    newdate.append(year[x]+month[x]+day[x])
sh_rent["Newdate"] = newdate
sh_rent["Newdate"]
sortedsh=sh_rent.sort_values(["Unit_Code","Newdate"])
sortedsh

C:\Users\Lena\Anaconda3\envs\threesix\lib\site-packages\ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,Property_Code,Date,Tenant_Code,Event,DateOccurred,Unit_Code,DateApply,DateApprove,DateSign,DateMoveIn,...,RentedEvent,UnRentedEvent,Status,Rent,Deposit,Sqft,Notes,Reason,MTM,Newdate
20872,sh,6/30/2014,t0017590,Rent Change,6/30/2014,AC1038,8/1/2013,NaN,8/1/2013,7/22/2010,...,0,0,0,889.0,59.0,0.0,NaN,NaN,0.0,20140630
22824,sh,8/1/2014,t0017590,Rent Change,8/1/2014,AC1038,8/1/2013,NaN,8/1/2013,7/22/2010,...,0,0,0,909.0,59.0,0.0,NaN,NaN,0.0,20140801
7398,sh,6/18/2015,t0025500,Rent Change,6/18/2015,AC1038,6/16/2015,6/16/2015,NaN,6/30/2015,...,0,0,6,990.0,0.0,0.0,NaN,NaN,NaN,20150618
48135,sh,3/15/2017,t0032418,Rent Change,3/15/2017,AC1038,2/22/2017,2/23/2017,3/3/2017,3/25/2017,...,0,0,2,1010.0,99.0,0.0,NaN,NaN,0.0,20170315
48692,sh,7/31/2018,t0033629,Rent Change,7/31/2018,AC1038,7/31/2017,7/31/2017,8/11/2017,8/24/2017,...,0,0,0,1020.0,911.0,0.0,NaN,NaN,0.0,20180731
74352,sh,8/31/2018,t0033629,Rent Change,8/31/2018,AC1038,7/31/2017,7/31/2017,8/11/2017,8/24/2017,...,0,0,0,1050.0,911.0,0.0,NaN,NaN,0.0,20180831
12342,sh,2/28/2014,t0017591,Rent Change,2/28/2014,AC1040,12/1/2013,NaN,12/1/2013,11/29/2011,...,0,0,0,861.0,169.0,0.0,NaN,NaN,-1.0,20140228
13687,sh,10/31/2015,t0021417,Rent Change,10/31/2015,AC1040,5/19/2014,5/30/2014,5/30/2014,6/15/2014,...,0,0,0,1015.0,99.0,0.0,NaN,NaN,-1.0,20151031
63479,sh,6/30/2017,t0021417,Rent Change,6/30/2017,AC1040,5/19/2014,5/30/2014,5/30/2014,6/15/2014,...,0,0,0,1025.0,99.0,0.0,NaN,NaN,0.0,20170630
20873,sh,6/30/2014,t0017565,Rent Change,6/30/2014,AC1041,7/1/2013,NaN,7/1/2013,6/24/2011,...,0,0,0,881.0,59.0,0.0,NaN,NaN,0.0,20140630
7729,sh,6/30/2015,t0017565,Rent Change,6/30/2015,AC1041,7/1/2013,NaN,7/1/2013,6/24/2011,...,0,0,0,990.0,59.0,0.0,NaN,NaN,0.0,20150630
56255,sh,6/17/2017,t0033439,Rent Change,6/17/2017,AC1041,6/16/2017,NaN,NaN,7/26/2017,...,0,0,6,1010.0,0.0,0.0,NaN,NaN,0.0,20170617
2770,sh,6/30/2018,t0033439,Rent Change,6/30/2018,AC1041,6/16/2017,6/20/2017,6/28/2017,7/26/2017,...,0,0,0,1030.0,809.0,0.0,NaN,NaN,0.0,20180630
48693,sh,7/31/2018,t0033439,Rent Change,7/31/2018,AC1041,6/16/2017,6/20/2017,6/28/2017,7/26/2017,...,0,0,0,1110.0,809.0,0.0,NaN,NaN,0.0,20180731
22825,sh,8/1/2014,t0022206,Rent Change,8/1/2014,AC1043,7/11/2014,7/14/2014,7/15/2014,7/15/2014,...,0,0,0,965.0,99.0,0.0,NaN,NaN,NaN,20140801
47465,sh,10/31/2016,t0026151,Rent Change,10/31/2016,AC1043,9/23/2015,9/24/2015,9/30/2015,9/30/2015,...,0,0,0,1000.0,399.0,0.0,NaN,NaN,NaN,20161031
61162,sh,10/31/2017,t0026151,Rent Change,10/31/2017,AC1043,9/23/2015,9/24/2015,9/30/2015,9/30/2015,...,0,0,0,1025.0,399.0,0.0,NaN,NaN,0.0,20171031
22826,sh,8/1/2014,t0017588,Rent Change,8/1/2014,AC1044,8/1/2013,NaN,8/1/2013,8/16/2010,...,0,0,0,861.0,59.0,0.0,NaN,NaN,-1.0,20140801
8692,sh,7/31/2015,t0017588,Rent Change,7/31/2015,AC1044,8/1/2013,NaN,8/1/2013,8/16/2010,...,0,0,0,896.0,59.0,0.0,NaN,NaN,0.0,20150731
23810,sh,7/31/2016,t0017588,Rent Change,7/31/2016,AC1044,8/1/2013,NaN,8/1/2013,8/16/2010,...,0,0,0,908.0,59.0,0.0,NaN,NaN,0.0,20160731
3628,sh,7/31/2017,t0017588,Rent Change,7/31/2017,AC1044,8/1/2013,NaN,8/1/2013,8/16/2010,...,0,0,0,933.0,59.0,0.0,NaN,NaN,0.0,20170731
48694,sh,7/31/2018,t0017588,Rent Change,7/31/2018,AC1044,8/1/2013,NaN,8/1/2013,8/16/2010,...,0,0,0,1033.0,59.0,0.0,NaN,NaN,0.0,20180731
17772,sh,4/30/2014,t0017589,Rent Change,4/30/2014,AC1046,5/1/2013,NaN,5/1/2013,5/1/2013,...,0,0,0,921.0,99.0,0.0,NaN,NaN,0.0,20140430
19770,sh,5/31/2016,t0025420,Rent Change,5/31/2016,AC1046,6/4/2015,6/5/2015,6/30/2015,6/29/2015,...,0,0,0,992.0,99.0,0.0,NaN,NaN,0.0,20160531
21960,sh,6/30/2016,t0025420,Rent Change,6/30/2016,AC1046,6/4/2015,6/5/2015,6/30/2015,6/29/2015,...,0,0,0,990.0,99.0,0.0,NaN,NaN,-1.0,20160630
23811,sh,7/31/2016,t0025420,Rent Change,7/31/2016,AC1046,6/4/2015,6/5/2015,6/30/2015,6/29/2015,...,0,0,0,1015.0,99.0,0.0,NaN,NaN,0.0,20160731
2771,sh,6/30/2018,t0032973,Rent Change,6/30/2018,AC1046,5/10/2017,5/22/2017,5/23/2017,6/30/2017,...,0,0,0,1017.0,99.0,0.0,NaN,NaN,0.0,20180630
48695,sh,7/31/2018,t0032973,Rent Change,7/31/2018,AC1046,5/10/2017,5/22/2017,5/23/2017,6/30/2017,...,0,0,0,1110.0,99.0,0.0,NaN,NaN,0.0,20180731
27536,sh,10/10/2014,t0023494,Rent Change,10/10/2014,AC1047,10/3/2014,10/3/2014,10/6/2014,10/10/2014,...,0,0,2,1200.0,0.0,0.0,NaN,NaN,0.0,20141010
58754,sh,1/18/2017,t0031775,Rent Change,1/18/2017,AC1047,1/13/2017,1/16/2017,NaN,2/15/2017,...,0,0,6,1210.0,99.0,0.0,NaN,NaN,0.0,20170118
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63793,sh,8/31/2017,t0017722,Rent Change,8/31/2017,WC5970G,10/1/2013,NaN,10/1/2013,9/8/2008,...,0,0,0,665.0,249.0,0.0,NaN,NaN,0.0,20170831
57197,sh,9/30/2017,t0017722,Rent Change,9/30/2017,WC5970G,10/1/2013,NaN,10/1/2013,9/8/2008,...,0,0,0,673.0,249.0,0.0,NaN,NaN,0.0,20170930
79790,sh,10/4/2018,t0040225,Rent Change,10/4/2018,WC5970G,10/2/2018,10/2/2018,NaN,10/10/2018,...,0,0,6,675.0,0.0,0.0,NaN,NaN,0.0,20181004
79801,sh,10/4/2018,t0043967,Rent Change,10/4/2018,WC5970G,8/3/2018,8/3/2018,NaN,10/31/2018,...,0,0,6,675.0,40.0,0.0,NaN,NaN,NaN,20181004
459,sh,10/16/2018,t0040974,Rent Change,10/16/2018,WC5970G,10/15/2018,10/16/2018,NaN,10/17/2018,...,0,0,6,675.0,0.0,0.0,NaN,NaN,0.0,20181016
10166,sh,1/31/2014,t0017723,Rent Change,1/31/2014,WC5970H,1/30/2013,NaN,1/30/2013,1/30/2013,...,0,0,0,550.0,99.0,0.0,NaN,NaN,0.0,20140131
16265,sh,2/29/2016,t0024706,Rent Change,2/29/2016,WC5970H,2/21/2015,2/21/2015,2/27/2015,2/28/2015,...,0,0,0,603.0,99.0,0.0,NaN,NaN,NaN,20160229
17024,sh,3/31/2016,t0024706,Rent Change,3/31/2016,WC5970H,2/21/2015,2/21/2015,2/27/2015,2/28/2015,...,0,0,0,620.0,99.0,0.0,NaN,NaN,0.0,20160331
61328,sh,2/28/2017,t0024706,Rent Change,2/28/2017,WC5970H,2/21/2015,2/21/2015,2/27/2015,2/28/2015,...,0,0,0,623.0,99.0,0.0,NaN,NaN,0.0,20170228
53060,sh,3/31/2017,t0024706,Rent Change,3/31/2017,WC5970H,2/21/2015,2/21/2015,2/27/2015,2/28/2015,...,0,0,0,645.0,99.0,0.0,NaN,NaN,0.0,20170331
49516,sh,3/3/2018,t0039163,Rent Change,3/3/2018,WC5970H,3/2/2018,NaN,NaN,5/31/2018,...,0,0,6,675.0,0.0,0.0,NaN,NaN,0.0,20180303
8714,sh,7/31/2015,t0022199,Rent Change,7/31/2015,WC5970I,7/10/2014,7/10/2014,7/22/2014,7/22/2014,...,0,0,0,605.0,99.0,0.0,NaN,NaN,0.0,20150731
50488,sh,9/14/2017,t0034612,Rent Change,9/14/2017,WC5970I,8/9/2017,8/9/2017,9/11/2017,9/30/2017,...,0,0,2,609.0,99.0,0.0,NaN,NaN,0.0,20170914
1003,sh,8/3/2018,t0040188,Rent Change,8/3/2018,WC5970I,6/24/2018,6/25/2018,7/27/2018,8/10/2018,...,0,0,2,675.0,99.0,0.0,NaN,NaN,0.0,20180803
23841,sh,7/31/2016,t0025813,Rent Change,7/31/2016,WC5970J,7/30/2015,7/30/2015,8/6/2015,8/7/2015,...,0,0,0,839.0,99.0,0.0,NaN,NaN,-1.0,20160731
25885,sh,8/23/2016,t0025813,Rent Change,8/23/2016,WC5970J,7/30/2015,7/30/2015,8/6/2015,8/7/2015,...,0,0,4,607.0,99.0,0.0,NaN,NaN,-1.0,20160823
63794,sh,8/31/2017,t0030854,Rent Change,8/31/2017,WC5970J,9/13/2016,9/15/2016,9/27/2016,9/30/2016,...,0,0,0,610.0,198.0,0.0,NaN,NaN,0.0,20170831
57198,sh,9/30/2017,t0030854,Rent Change,9/30/2017,WC5970J,9/13/2016,9/15/2016,9/27/2016,9/30/2016,...,0,0,0,634.0,198.0,0.0,NaN,NaN,0.0,20170930
78970,sh,9/30/2018,t0030854,Rent Change,9/30/2018,WC5970J,9/13/2016,9/15/2016,9/27/2016,9/30/2016,...,0,0,0,675.0,198.0,0.0,NaN,NaN,0.0,20180930
17807,sh,4/30/2014,t0017726,Rent Change,4/30/2014,WC5970K,5/1/2012,NaN,5/1/2012,5/1/2012,...,0,0,0,539.0,79.0,0.0,NaN,NaN,0.0,20140430
6146,sh,4/30/2015,t0017726,Rent Change,4/30/2015,WC5970K,5/1/2012,NaN,5/1/2012,5/1/2012,...,0,0,0,564.0,79.0,0.0,NaN,NaN,0.0,20150430
18447,sh,4/20/2016,t0028499,Rent Change,4/20/2016,WC5970K,2/17/2016,NaN,NaN,4/29/2016,...,0,0,9,597.0,0.0,0.0,NaN,NaN,0.0,20160420
58300,sh,4/12/2017,t0032570,Rent Change,4/12/2017,WC5970K,3/15/2017,3/17/2017,4/7/2017,5/26/2017,...,0,0,2,609.0,99.0,0.0,NaN,NaN,0.0,20170412
51535,sh,5/31/2018,t0032570,Rent Change,5/31/2018,WC5970K,3/15/2017,3/17/2017,4/7/2017,5/12/2017,...,0,0,0,632.0,99.0,0.0,NaN,NaN,0.0,20180531
2820,sh,6/30/2018,t0032570,Rent Change,6/30/2018,WC5970K,3/15/2017,3/17/2017,4/7/2017,5/12/2017,...,0,0,0,645.0,99.0,0.0,NaN,NaN,0.0,20180630
17025,sh,3/31/2016,t0024976,Rent Change,3/31/2016,WC5970L,4/4/2015,4/6/2015,4/7/2015,4/20/2015,...,0,0,0,621.0,99.0,0.0,NaN,NaN,0.0,20160331
18806,sh,5/1/2016,t0024976,Rent Change,5/1/2016,WC5970L,4/4/2015,4/6/2015,4/7/2015,4/20/2015,...,0,0,0,777.0,99.0,0.0,NaN,NaN,0.0,20160501
45431,sh,10/18/2016,t0031084,Rent Change,10/18/2016,WC5970L,10/13/2016,10/14/2016,NaN,10/31/2016,...,0,0,6,609.0,99.0,0.0,NaN,NaN,0.0,20161018
52784,sh,12/31/2016,t0031084,Rent Change,12/31/2016,WC5970L,10/13/2016,10/14/2016,10/18/2016,10/31/2016,...,0,0,0,609.0,99.0,0.0,NaN,NaN,0.0,20161231
65337,sh,10/31/2017,t0031084,Rent Change,10/31/2017,WC5970L,10/13/2016,10/14/2016,10/18/2016,10/31/2016,...,0,0,0,634.0,99.0,0.0,NaN,NaN,0.0,20171031

In [156]:
r = []
chrent = []
lrent = []
for x in range(len(sortedsh)):
    unitcode = sortedsh["Unit_Code"].iloc[x]
    prevunit = sortedsh["Unit_Code"].iloc[x-1]
    if unitcode==prevunit:
        rent = sortedsh["Rent"].iloc[x]
        prevrent = sortedsh["Rent"].iloc[x-1]
        changerent = rent-prevrent
        chrent.append(changerent)
    else:
        chrent.append(0)
sortedsh["chrent"]=chrent
sortedsh

,Property_Code,Date,Tenant_Code,Event,DateOccurred,Unit_Code,DateApply,DateApprove,DateSign,DateMoveIn,...,UnRentedEvent,Status,Rent,Deposit,Sqft,Notes,Reason,MTM,Newdate,chrent
20872,sh,6/30/2014,t0017590,Rent Change,6/30/2014,AC1038,8/1/2013,NaN,8/1/2013,7/22/2010,...,0,0,889.0,59.0,0.0,NaN,NaN,0.0,20140630,0.0
22824,sh,8/1/2014,t0017590,Rent Change,8/1/2014,AC1038,8/1/2013,NaN,8/1/2013,7/22/2010,...,0,0,909.0,59.0,0.0,NaN,NaN,0.0,20140801,20.0
7398,sh,6/18/2015,t0025500,Rent Change,6/18/2015,AC1038,6/16/2015,6/16/2015,NaN,6/30/2015,...,0,6,990.0,0.0,0.0,NaN,NaN,NaN,20150618,81.0
48135,sh,3/15/2017,t0032418,Rent Change,3/15/2017,AC1038,2/22/2017,2/23/2017,3/3/2017,3/25/2017,...,0,2,1010.0,99.0,0.0,NaN,NaN,0.0,20170315,20.0
48692,sh,7/31/2018,t0033629,Rent Change,7/31/2018,AC1038,7/31/2017,7/31/2017,8/11/2017,8/24/2017,...,0,0,1020.0,911.0,0.0,NaN,NaN,0.0,20180731,10.0
74352,sh,8/31/2018,t0033629,Rent Change,8/31/2018,AC1038,7/31/2017,7/31/2017,8/11/2017,8/24/2017,...,0,0,1050.0,911.0,0.0,NaN,NaN,0.0,20180831,30.0
12342,sh,2/28/2014,t0017591,Rent Change,2/28/2014,AC1040,12/1/2013,NaN,12/1/2013,11/29/2011,...,0,0,861.0,169.0,0.0,NaN,NaN,-1.0,20140228,0.0
13687,sh,10/31/2015,t0021417,Rent Change,10/31/2015,AC1040,5/19/2014,5/30/2014,5/30/2014,6/15/2014,...,0,0,1015.0,99.0,0.0,NaN,NaN,-1.0,20151031,154.0
63479,sh,6/30/2017,t0021417,Rent Change,6/30/2017,AC1040,5/19/2014,5/30/2014,5/30/2014,6/15/2014,...,0,0,1025.0,99.0,0.0,NaN,NaN,0.0,20170630,10.0
20873,sh,6/30/2014,t0017565,Rent Change,6/30/2014,AC1041,7/1/2013,NaN,7/1/2013,6/24/2011,...,0,0,881.0,59.0,0.0,NaN,NaN,0.0,20140630,0.0
7729,sh,6/30/2015,t0017565,Rent Change,6/30/2015,AC1041,7/1/2013,NaN,7/1/2013,6/24/2011,...,0,0,990.0,59.0,0.0,NaN,NaN,0.0,20150630,109.0
56255,sh,6/17/2017,t0033439,Rent Change,6/17/2017,AC1041,6/16/2017,NaN,NaN,7/26/2017,...,0,6,1010.0,0.0,0.0,NaN,NaN,0.0,20170617,20.0
2770,sh,6/30/2018,t0033439,Rent Change,6/30/2018,AC1041,6/16/2017,6/20/2017,6/28/2017,7/26/2017,...,0,0,1030.0,809.0,0.0,NaN,NaN,0.0,20180630,20.0
48693,sh,7/31/2018,t0033439,Rent Change,7/31/2018,AC1041,6/16/2017,6/20/2017,6/28/2017,7/26/2017,...,0,0,1110.0,809.0,0.0,NaN,NaN,0.0,20180731,80.0
22825,sh,8/1/2014,t0022206,Rent Change,8/1/2014,AC1043,7/11/2014,7/14/2014,7/15/2014,7/15/2014,...,0,0,965.0,99.0,0.0,NaN,NaN,NaN,20140801,0.0
47465,sh,10/31/2016,t0026151,Rent Change,10/31/2016,AC1043,9/23/2015,9/24/2015,9/30/2015,9/30/2015,...,0,0,1000.0,399.0,0.0,NaN,NaN,NaN,20161031,35.0
61162,sh,10/31/2017,t0026151,Rent Change,10/31/2017,AC1043,9/23/2015,9/24/2015,9/30/2015,9/30/2015,...,0,0,1025.0,399.0,0.0,NaN,NaN,0.0,20171031,25.0
22826,sh,8/1/2014,t0017588,Rent Change,8/1/2014,AC1044,8/1/2013,NaN,8/1/2013,8/16/2010,...,0,0,861.0,59.0,0.0,NaN,NaN,-1.0,20140801,0.0
8692,sh,7/31/2015,t0017588,Rent Change,7/31/2015,AC1044,8/1/2013,NaN,8/1/2013,8/16/2010,...,0,0,896.0,59.0,0.0,NaN,NaN,0.0,20150731,35.0
23810,sh,7/31/2016,t0017588,Rent Change,7/31/2016,AC1044,8/1/2013,NaN,8/1/2013,8/16/2010,...,0,0,908.0,59.0,0.0,NaN,NaN,0.0,20160731,12.0
3628,sh,7/31/2017,t0017588,Rent Change,7/31/2017,AC1044,8/1/2013,NaN,8/1/2013,8/16/2010,...,0,0,933.0,59.0,0.0,NaN,NaN,0.0,20170731,25.0
48694,sh,7/31/2018,t0017588,Rent Change,7/31/2018,AC1044,8/1/2013,NaN,8/1/2013,8/16/2010,...,0,0,1033.0,59.0,0.0,NaN,NaN,0.0,20180731,100.0
17772,sh,4/30/2014,t0017589,Rent Change,4/30/2014,AC1046,5/1/2013,NaN,5/1/2013,5/1/2013,...,0,0,921.0,99.0,0.0,NaN,NaN,0.0,20140430,0.0
19770,sh,5/31/2016,t0025420,Rent Change,5/31/2016,AC1046,6/4/2015,6/5/2015,6/30/2015,6/29/2015,...,0,0,992.0,99.0,0.0,NaN,NaN,0.0,20160531,71.0
21960,sh,6/30/2016,t0025420,Rent Change,6/30/2016,AC1046,6/4/2015,6/5/2015,6/30/2015,6/29/2015,...,0,0,990.0,99.0,0.0,NaN,NaN,-1.0,20160630,-2.0
23811,sh,7/31/2016,t0025420,Rent Change,7/31/2016,AC1046,6/4/2015,6/5/2015,6/30/2015,6/29/2015,...,0,0,1015.0,99.0,0.0,NaN,NaN,0.0,20160731,25.0
2771,sh,6/30/2018,t0032973,Rent Change,6/30/2018,AC1046,5/10/2017,5/22/2017,5/23/2017,6/30/2017,...,0,0,1017.0,99.0,0.0,NaN,NaN,0.0,20180630,2.0
48695,sh,7/31/2018,t0032973,Rent Change,7/31/2018,AC1046,5/10/2017,5/22/2017,5/23/2017,6/30/2017,...,0,0,1110.0,99.0,0.0,NaN,NaN,0.0,20180731,93.0
27536,sh,10/10/2014,t0023494,Rent Change,10/10/2014,AC1047,10/3/2014,10/3/2014,10/6/2014,10/10/2014,...,0,2,1200.0,0.0,0.0,NaN,NaN,0.0,20141010,0.0
58754,sh,1/18/2017,t0031775,Rent Change,1/18/2017,AC1047,1/13/2017,1/16/2017,NaN,2/15/2017,...,0,6,1210.0,99.0,0.0,NaN,NaN,0.0,20170118,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63793,sh,8/31/2017,t0017722,Rent Change,8/31/2017,WC5970G,10/1/2013,NaN,10/1/2013,9/8/2008,...,0,0,665.0,249.0,0.0,NaN,NaN,0.0,20170831,17.0
57197,sh,9/30/2017,t0017722,Rent Change,9/30/2017,WC5970G,10/1/2013,NaN,10/1/2013,9/8/2008,...,0,0,673.0,249.0,0.0,NaN,NaN,0.0,20170930,8.0
79790,sh,10/4/2018,t0040225,Rent Change,10/4/2018,WC5970G,10/2/2018,10/2/2018,NaN,10/10/2018,...,0,6,675.0,0.0,0.0,NaN,NaN,0.0,20181004,2.0
79801,sh,10/4/2018,t0043967,Rent Change,10/4/2018,WC5970G,8/3/2018,8/3/2018,NaN,10/31/2018,...,0,6,675.0,40.0,0.0,NaN,NaN,NaN,20181004,0.0
459,sh,10/16/2018,t0040974,Rent Change,10/16/2018,WC5970G,10/15/2018,10/16/2018,NaN,10/17/2018,...,0,6,675.0,0.0,0.0,NaN,NaN,0.0,20181016,0.0
10166,sh,1/31/2014,t0017723,Rent Change,1/31/2014,WC5970H,1/30/2013,NaN,1/30/2013,1/30/2013,...,0,0,550.0,99.0,0.0,NaN,NaN,0.0,20140131,0.0
16265,sh,2/29/2016,t0024706,Rent Change,2/29/2016,WC5970H,2/21/2015,2/21/2015,2/27/2015,2/28/2015,...,0,0,603.0,99.0,0.0,NaN,NaN,NaN,20160229,53.0
17024,sh,3/31/2016,t0024706,Rent Change,3/31/2016,WC5970H,2/21/2015,2/21/2015,2/27/2015,2/28/2015,...,0,0,620.0,99.0,0.0,NaN,NaN,0.0,20160331,17.0
61328,sh,2/28/2017,t0024706,Rent Change,2/28/2017,WC5970H,2/21/2015,2/21/2015,2/27/2015,2/28/2015,...,0,0,623.0,99.0,0.0,NaN,NaN,0.0,20170228,3.0
53060,sh,3/31/2017,t0024706,Rent Change,3/31/2017,WC5970H,2/21/2015,2/21/2015,2/27/2015,2/28/2015,...,0,0,645.0,99.0,0.0,NaN,NaN,0.0,20170331,22.0
49516,sh,3/3/2018,t0039163,Rent Change,3/3/2018,WC5970H,3/2/2018,NaN,NaN,5/31/2018,...,0,6,675.0,0.0,0.0,NaN,NaN,0.0,20180303,30.0
8714,sh,7/31/2015,t0022199,Rent Change,7/31/2015,WC5970I,7/10/2014,7/10/2014,7/22/2014,7/22/2014,...,0,0,605.0,99.0,0.0,NaN,NaN,0.0,20150731,0.0
50488,sh,9/14/2017,t0034612,Rent Change,9/14/2017,WC5970I,8/9/2017,8/9/2017,9/11/2017,9/30/2017,...,0,2,609.0,99.0,0.0,NaN,NaN,0.0,20170914,4.0
1003,sh,8/3/2018,t0040188,Rent Change,8/3/2018,WC5970I,6/24/2018,6/25/2018,7/27/2018,8/10/2018,...,0,2,675.0,99.0,0.0,NaN,NaN,0.0,20180803,66.0
23841,sh,7/31/2016,t0025813,Rent Change,7/31/2016,WC5970J,7/30/2015,7/30/2015,8/6/2015,8/7/2015,...,0,0,839.0,99.0,0.0,NaN,NaN,-1.0,20160731,0.0
25885,sh,8/23/2016,t0025813,Rent Change,8/23/2016,WC5970J,7/30/2015,7/30/2015,8/6/2015,8/7/2015,...,0,4,607.0,99.0,0.0,NaN,NaN,-1.0,20160823,-232.0
63794,sh,8/31/2017,t0030854,Rent Change,8/31/2017,WC5970J,9/13/2016,9/15/2016,9/27/2016,9/30/2016,...,0,0,610.0,198.0,0.0,NaN,NaN,0.0,20170831,3.0
57198,sh,9/30/2017,t0030854,Rent Change,9/30/2017,WC5970J,9/13/2016,9/15/2016,9/27/2016,9/30/2016,...,0,0,634.0,198.0,0.0,NaN,NaN,0.0,20170930,24.0
78970,sh,9/30/2018,t0030854,Rent Change,9/30/2018,WC5970J,9/13/2016,9/15/2016,9/27/2016,9/30/2016,...,0,0,675.0,198.0,0.0,NaN,NaN,0.0,20180930,41.0
17807,sh,4/30/2014,t0017726,Rent Change,4/30/2014,WC5970K,5/1/2012,NaN,5/1/2012,5/1/2012,...,0,0,539.0,79.0,0.0,NaN,NaN,0.0,20140430,0.0
6146,sh,4/30/2015,t0017726,Rent Change,4/30/2015,WC5970K,5/1/2012,NaN,5/1/2012,5/1/2012,...,0,0,564.0,79.0,0.0,NaN,NaN,0.0,20150430,25.0
18447,sh,4/20/2016,t0028499,Rent Change,4/20/2016,WC5970K,2/17/2016,NaN,NaN,4/29/2016,...,0,9,597.0,0.0,0.0,NaN,NaN,0.0,20160420,33.0
58300,sh,4/12/2017,t0032570,Rent Change,4/12/2017,WC5970K,3/15/2017,3/17/2017,4/7/2017,5/26/2017,...,0,2,609.0,99.0,0.0,NaN,NaN,0.0,20170412,12.0
51535,sh,5/31/2018,t0032570,Rent Change,5/31/2018,WC5970K,3/15/2017,3/17/2017,4/7/2017,5/12/2017,...,0,0,632.0,99.0,0.0,NaN,NaN,0.0,20180531,23.0
2820,sh,6/30/2018,t0032570,Rent Change,6/30/2018,WC5970K,3/15/2017,3/17/2017,4/7/2017,5/12/2017,...,0,0,645.0,99.0,0.0,NaN,NaN,0.0,20180630,13.0
17025,sh,3/31/2016,t0024976,Rent Change,3/31/2016,WC5970L,4/4/2015,4/6/2015,4/7/2015,4/20/2015,...,0,0,621.0,99.0,0.0,NaN,NaN,0.0,20160331,0.0
18806,sh,5/1/2016,t0024976,Rent Change,5/1/2016,WC5970L,4/4/2015,4/6/2015,4/7/2015,4/20/2015,...,0,0,777.0,99.0,0.0,NaN,NaN,0.0,20160501,156.0
45431,sh,10/18/2016,t0031084,Rent Change,10/18/2016,WC5970L,10/13/2016,10/14/2016,NaN,10/31/2016,...,0,6,609.0,99.0,0.0,NaN,NaN,0.0,20161018,-168.0
52784,sh,12/31/2016,t0031084,Rent Change,12/31/2016,WC5970L,10/13/2016,10/14/2016,10/18/2016,10/31/2016,...,0,0,609.0,99.0,0.0,NaN,NaN,0.0,20161231,0.0
65337,sh,10/31/2017,t0031084,Rent Change,10/31/2017,WC5970L,10/13/2016,10/14/2016,10/18/2016,10/31/2016,...,0,0,634.0,99.0,0.0,NaN,NaN,0.0,20171031,25.0

In [25]:
sortedsh["Rent"].iloc[0]

715.0